### ISSUE TITLE
"Apply to slot 1" button not working

### ISSUE THREAD

**Issue by TerraTR** [RedDot-3ND7355/reWASD#1]
![image](https://github.com/RedDot-3ND7355/reWASD/assets/92224509/34e3d44a-f3db-4089-a952-d4b0a7ae03b9)
nothing happens when i click that button idk if its a problem on my side

**Comment by RedDot-3ND7355** [comment]
as-tu verifier les proprieter de les 2 dll? Pour voir s'ils sont blocker ou pas par windows.
Aussi j'ai jamais tester sur la version VF du program. Donc verifie les dll en premiers puis si sa marche pas, reinstalle le en anglais.

**Comment by andrewCOL1** [comment]
> as-tu verifier les proprieter de les 2 dll? Pour voir s'ils sont blocker ou pas par windows. Aussi j'ai jamais tester sur la version VF du program. Donc verifie les dll en premiers puis si sa marche pas, reinstalle le en anglais.

I have the same problem. DLLs are unlocked and my program version is English.

**Comment by RedDot-3ND7355** [comment]
Will have a look when I get the time today and then I'll update the crack.

**Comment by JJohanXz** [comment]
The same

**Comment by RedDot-3ND7355** [comment]
@JJohanXz @TerraTR @andrewCOL1  any of you have discord?

**Comment by JJohanXz** [comment]
@RedDot-3ND7355 

Johan_fwck

**Comment by RedDot-3ND7355** [comment]
> @RedDot-3ND7355
> 
> Johan_fwck

Can't add you
![image](https://github.com/RedDot-3ND7355/reWASD/assets/6676924/c3bf15e2-63f8-447d-a138-46be0e11d8a2)

**Comment by JJohanXz** [comment]
@RedDot-3ND7355 

Discord was crashing, please try again.

**Comment by TerraTR** [comment]
![image](https://github.com/RedDot-3ND7355/reWASD/assets/92224509/6b841ca5-7f54-4469-8b5f-680d322dd5b5)

**Comment by RedDot-3ND7355** [comment]
@TerraTR @JJohanXz  added you both

**Comment by Sadewprabuddha** [comment]
same ..

**Comment by Feronym** [comment]
Hey @RedDot-3ND7355, I have same problem here. If you need another tester, I'm here to help :p (dc: feronym)... If you're gonna be able to fix this, I'm gonna fu*king love you. Thanks in advance :*

**Comment by danilobrazil564** [comment]
mine doesn't want to apply

**Comment by 14cky** [comment]
same problem, i tried it on windows 10 and windows 11, but it just wont apply

**Comment by 14cky** [comment]
apparently, it cant check license. If you try to apply config using reWASD Junior app, it will give you "Checking license error"

**Comment by scanlan897** [comment]
same

**Comment by RedDot-3ND7355** [comment]
Scrapped the entire crack and started from scratch. Will have it ready soon! :)
Testers will be contacted when new test dll's are ready!

**Comment by Ritsop** [comment]
hey, i can help test my user is mmyles

**Comment by titeta231** [comment]
> Scrapped the entire crack and started from scratch. Will have it ready soon! :) Testers will be contacted when new test dll's are ready!

Can I help with testing this crack on Steam Deck?

**Comment by RedDot-3ND7355** [comment]
> hey, i can help test my user is mmyles

Added!



> > Scrapped the entire crack and started from scratch. Will have it ready soon! :) Testers will be contacted when new test dll's are ready!
> 
> Can I help with testing this crack on Steam Deck?

does rewasd work on steam deck? or with steam deck?
nonetheless, you can test yes :)
drop me your discord user

**Comment by triatomic** [comment]
I can also help with testing on latest windows 11 machine
discord: azura6167

**Comment by Nortorn** [comment]
it worked for me until i restarted the pc.

If you are open for more testers, let me know via discord; nie.ka

I've got both win 10 and 11 machines and a variety of controllers with a few saved mappings

**Comment by Nabeeh-AlSawaf** [comment]
idk if this helps but yesterday i faced the same problem of clicking the Apply to slot 1 doing nothing, i didn't have internet connection at that time, but when i restarted my pc while having an active internet connection (that connects when the pc is booted up) the problem disappeared and i was able to apply to slot again. 
idk how helpful that would be but internet connection was the lone difference for me for when it cant apply vs when it can.

**Comment by RedDot-3ND7355** [comment]
@Nabeeh-AlSawaf  that's what I was trying to fix. And I did just now today.
Will be updating the crack later today or tomorrow.

**Comment by sdad1221d1** [comment]
i have the same thing

**Comment by danilobrazil564** [comment]
you will notify here when you use it
@RedDot-3ND7355

**Comment by kidnamedfrank** [comment]
i can't wait for the new fix!

**Comment by kidnamedfrank** [comment]
if you need anymore testers, im here! kidnamedfrank_ is my username :) @RedDot-3ND7355

**Comment by craqedfn** [comment]
wwwwe waiting sir @RedDot-3ND7355

**Comment by craqedfn** [comment]
my discord is nathanffn btw

**Comment by kidnamedfrank** [comment]
> RedDot-3ND7355

be patient man

**Comment by RedDot-3ND7355** [comment]
Managed to find a workaround for the license, but now requires another edit that will require a bit more time.
Due to tools not being powerful enough (memory-wise) to apply the huge edit I want to do xD

Will update ya'll when I got a test version up!

**Comment by kidnamedfrank** [comment]
> Managed to find a workaround for the license, but now requires another edit that will require a bit more time. Due to tools not being powerful enough (memory-wise) to apply the huge edit I want to do xD
> 
> Will update ya'll when I got a test version up!

Alright, Thank you!

**Comment by craqedfn** [comment]
> Managed to find a workaround for the license, but now requires another edit that will require a bit more time. Due to tools not being powerful enough (memory-wise) to apply the huge edit I want to do xD
> 
> Will update ya'll when I got a test version up!

How long will this be?

**Comment by kidnamedfrank** [comment]
> > Managed to find a workaround for the license, but now requires another edit that will require a bit more time. Due to tools not being powerful enough (memory-wise) to apply the huge edit I want to do xD
> > Will update ya'll when I got a test version up!
> 
> How long will this be?

Probably awhile, From what it looks like.

**Comment by kidnamedfrank** [comment]
Hate to bother, but how's progress? @RedDot-3ND7355

**Comment by craqedfn** [comment]
> Hate to bother, but how's progress? @RedDot-3ND7355

wondering same thing right now

**Comment by kidnamedfrank** [comment]
https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.

**Comment by RedDot-3ND7355** [comment]
> https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.

people that will find out that It doesn't work 100%
But other that paid for license for not the features will enjoy it fully :)

**Comment by kidnamedfrank** [comment]
****

> > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> 
> people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)

Yeah, speaking of which.. How's development for the fix? :)

**Comment by RedDot-3ND7355** [comment]
> > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > 
> > 
> > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> 
> Yeah, speaking of which.. How's development for the fix? :)

going to have to patch it on runtime to make the crack work. Sadly, this may cause a false-positive for Antiviruses.
Will keep ya'll posted if I get it to work :)

**Comment by kidnamedfrank** [comment]
> > > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > > 
> > > 
> > > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> > 
> > 
> > Yeah, speaking of which.. How's development for the fix? :)
> 
> going to have to patch it on runtime to make the crack work. Sadly, this may cause a false-positive for Antiviruses. Will keep ya'll posted if I get it to work :)

Alrighty, keep up the good work!

**Comment by X-49** [comment]
> > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > 
> > 
> > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> 
> Yeah, speaking of which.. How's development for the fix? :)

By the way, you can stop asking RedDot about this every day, I think he will not forget to notify us all if there is any news about the crack.

If you really need a crack, then the network has versions 6.6 and 5.2 with fully unlocked functionality. And the 5.2 version can simply be launched without using dnSpy, which is convenient.

**Comment by kidnamedfrank** [comment]
> > > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > > 
> > > 
> > > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> > 
> > 
> > Yeah, speaking of which.. How's development for the fix? :)
> 
> By the way, you can stop asking RedDot about this every day, I think he will not forget to notify us all if there is any news about the crack.
> 
> If you really need a crack, then the network has versions 6.6 and 5.2 with fully unlocked functionality. And the 5.2 version can simply be launched without using dnSpy, which is convenient.

Could you link them?

**Comment by sdad1221d1** [comment]
> > > > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > > > 
> > > > 
> > > > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> > > 
> > > 
> > > Yeah, speaking of which.. How's development for the fix? :)
> > 
> > 
> > By the way, you can stop asking RedDot about this every day, I think he will not forget to notify us all if there is any news about the crack.
> > If you really need a crack, then the network has versions 6.6 and 5.2 with fully unlocked functionality. And the 5.2 version can simply be launched without using dnSpy, which is convenient.
> 
> Could you link them?

https://github.com/EugeneSunrise/reWASD/releases

**Comment by iam-siphon** [comment]
> > > > > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > > > > 
> > > > > 
> > > > > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> > > > 
> > > > 
> > > > Yeah, speaking of which.. How's development for the fix? :)
> > > 
> > > 
> > > By the way, you can stop asking RedDot about this every day, I think he will not forget to notify us all if there is any news about the crack.
> > > If you really need a crack, then the network has versions 6.6 and 5.2 with fully unlocked functionality. And the 5.2 version can simply be launched without using dnSpy, which is convenient.
> > 
> > 
> > Could you link them?
> 
> https://github.com/EugeneSunrise/reWASD/releases

@kidnamedfrank  i forgot to link the v5.2 one sry https://wdho.ru/dzPJ 
make sure to use a ad blocker

**Comment by kidnamedfrank** [comment]
> > > > https://www.reddit.com/r/PiratedGames/comments/18og0wr/rewasd_a_game_controller_remapping_tool_has_been/ Alot of people are seeing this lol.
> > > 
> > > 
> > > people that will find out that It doesn't work 100% will be sad But others that paid for license for not the features will enjoy it fully :)
> > 
> > 
> > Yeah, speaking of which.. How's development for the fix? :)
> 
> By the way, you can stop asking RedDot about this every day, I think he will not forget to notify us all if there is any news about the crack.
> 
> If you really need a crack, then the network has versions 6.6 and 5.2 with fully unlocked functionality. And the 5.2 version can simply be launched without using dnSpy, which is convenient.

Could you send links?

**Comment by NiffirgkcaJ** [comment]
It's kind of a shame that it stopped working for unlicensed folks, though I'm hopeful. :(

Happy Holidays!

**Comment by TudorHH3000** [comment]
@RedDot-3ND7355 if ya need another tester im up to help u as i got a ds4 controller and im trying to emulate a controller with kbm (my discord user is tudorhh3000 or u can try FUCK#1100 if the other name does not work)

**Comment by ahmadabdullah366** [comment]
> It's kind of a shame that it stopped working for unlicensed folks, though I'm hopeful. :(
> 
> Happy Holidays!

I dont get it, It's working fine for me, Gmapade mapping working flawlessly, Mobile controller isn't, didn't try anything else.

**Comment by elite8283** [comment]
> @JJohanXz @TerraTR @andrewCOL1 any of you have discord? I'll be making debug versions to prompt the results.

can you add mee too? its ''elitefenyx''

**Comment by SmarterJoker** [comment]
Same, I am looking to have assistance in this matter as well, what discord may I message you at?

**Comment by Beanos3606** [comment]
Any updates. It's been too long. I can help if you want.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
