### ISSUE TITLE
It works perfect but 30 days check?

### ISSUE THREAD

**Issue by Trex386** [RedDot-3ND7355/reWASD#10]
Thank you, it works great. REWASD check licenses once every 30 days. Would this shut down the crack or still working after the checking?

**Comment by RedDot-3ND7355** [comment]
Probably an int check for once every month on the reWASDService to renew the license file.

Just sucks I can't reverse the reWASDService completely.

**Comment by Trex386** [comment]
Hopefully your method will work after the int check every month?

**Comment by psoizzac** [comment]
> Hopefully your method will work after the int check every month?

Just use Tiny Fire Wall  to block it calling home  - https://tinywall.pados.hu/download.php      

been using it and still have not got the 30 day check.

**Comment by Trex386** [comment]
> > Hopefully your method will work after the int check every month?
> 
> Just use Tiny Fire Wall to block it calling home - https://tinywall.pados.hu/download.php
> 
> been using it and still have not got the 30 day check. - Also Red let me know if this is against your uses for the forum log and i can take it down.

I thought you cant block REWASD Internet access. It is needed everytime you open the app in order to work.

**Comment by psoizzac** [comment]
> I thought you cant block REWASD Internet access. It is needed everytime you open the app in order to work.

 it's your decision and opinion and responsibility to take my testimony as valid or not.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
