### ISSUE TITLE
Expired on January 1, 2024

### ISSUE THREAD

**Issue by Zatermelon** [RedDot-3ND7355/reWASD#11]
I was able to use it normally yesterday without any problems, but when I tried to use it today, clicking on the application did not respond. Perhaps it was because there was an additional pop-up window when I opened it? Or it could be a hot fix checking the activated parts
![image](https://github.com/RedDot-3ND7355/reWASD/assets/49584890/d71982f1-6a3a-4bf6-a561-37e8fbf9bdc5)
After closing the pop-up window, there is no response after clicking on the application in the bottom left corner
![image](https://github.com/RedDot-3ND7355/reWASD/assets/49584890/69236c53-938b-4768-b3d0-ab5d8b02e7d0)
This is the activation information
![image](https://github.com/RedDot-3ND7355/reWASD/assets/49584890/4ad0fa69-ac0c-440b-acbb-b2b20c8693fc)

**Comment by darkqem** [comment]
same problem

**Comment by RedDot-3ND7355** [comment]
The silent update probably replaced one of the 2 dll's. 

Reput the crack in and see if it works.

**Comment by gpx0528** [comment]
I uninstalled and re downloaded the software, and then imported the program into a file, but it still doesn't wor

**Comment by narubox** [comment]
Same Problem and unistalled and re install dont work now :c

**Comment by Trex386** [comment]
Did it work before?

**Comment by Volshebnyy** [comment]
не работает кнопка применить на слот ,что делать?

**Comment by Stik3r** [comment]
> не работает кнопка применить на слот ,что делать?

Данный кряк пока не работает, автор писал в readme, ждем пока он починит, есть другой с версией чуть постарее 
https://github.com/EugeneSunrise/reWASD/releases

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
