### ISSUE TITLE
Radial Menu not showing

### ISSUE THREAD

**Issue by moiian** [RedDot-3ND7355/reWASD#13]
I am licensed user without Radial Menu feature. 
The Radial Menu feature did unlock, and the keybinding in Shift Radial Menu layer work well.
But no any radial menu or icon show, just like it is a general Shift Layer. Any radial menu navigation control are not working.
I have set any necessary setting in the software.

**Comment by psoizzac** [comment]
> I am licensed user (((without)))) Radial Menu feature. The Radial Menu feature did unlock.    Answer: This edit does not unlock the functions rather, you must buy the functions to use it with this applied edit. - Consider it (A Offline) mode and back up your license data to a External for future use. also keep a firewall on you so it doesn't silently call home.

**Comment by psoizzac** [comment]
> When it fails its monthly recheck, you just overwrite the dlls and it works again?? Regards

That is a second option aye.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
