### ISSUE TITLE
reWASD buy message

### ISSUE THREAD

**Issue by MrT3kila** [RedDot-3ND7355/reWASD#14]
Hello friend, after formatting my PC, I installed reWASD crack and used it until 1 week (today) and this message in the photo appeared, I already reinstalled it and put the crack again but this message continues to appear (reWASD 770-8447) how can I resolve this ? Or if you have another version with the crack but on reWASD 7, could you send it to me? Thank you for the patience
![image](https://github.com/RedDot-3ND7355/reWASD/assets/132508152/6ecb2d1e-6b09-48d6-a025-4303856927ec)

**Comment by MrT3kila** [comment]
![image](https://github.com/RedDot-3ND7355/reWASD/assets/132508152/7ce75315-67a0-4cf6-8fa1-252fbd693a1c)
in english

**Comment by RedDot-3ND7355** [comment]
Trial expired. You don't own a license.

**Comment by Mr-Nobody1** [comment]
> Trial expired. You don't own a license.

What? Can we use the Trail with your method again or is it over for good?

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
