### ISSUE TITLE
One Question for reWASD crack 

### ISSUE THREAD

**Issue by MrT3kila** [RedDot-3ND7355/reWASD#15]
For those who only have reWASD without any purchased features, when playing the crack and with this version 770-8447 installed does it unlock the features?

**Comment by RedDot-3ND7355** [comment]
It should unlock features. Make sure to read the readme if it's not working.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
