### ISSUE TITLE
problem with rewasd

### ISSUE THREAD

**Issue by bbb8993** [RedDot-3ND7355/reWASD#17]
i download this program for you all good and after a single day of use I received this error, I am attaching the picture
![licentta](https://github.com/RedDot-3ND7355/reWASD/assets/156777058/8235ccc8-fdab-4583-b4a2-2370ca0ac938)

**Comment by Trex386** [comment]
You need to buy the license first then apply dlls.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
