### ISSUE TITLE
Didnt work crack properly

### ISSUE THREAD

**Issue by kvisti** [RedDot-3ND7355/reWASD#18]
I have this problem, I need to reinstall rewasd every time I start the computer, that’s only way crack works. If you don’t do this, then click apply at the bottom, the program thinks, but nothing happens, is there a solution to this problem? Before this, the crack worked well for about a month

**Comment by kvisti** [comment]
i have license

**Comment by RedDot-3ND7355** [comment]
> i have license

Each month, re-apply the crack.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
