### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by WubTheGame** [RedDot-3ND7355/reWASD#19]
Hello, I'm interested in using this, but I'm not clear on how/for what it's to be used.

This "crack" only works for licensed users. That's what the readme.md says. But it seems to me that some issues are saying otherwise? But otherwise, does this then allow one license to be used on multiple devices, or how exactly does it all work? What's the point of a "crack" if you still need to pay for a license? I appreciate that there are older versions ready for free and this one's underway, but I'm still curious what's up here.

Thank you for your work.

**Comment by RedDot-3ND7355** [comment]
The actual license "crack" is being worked on.

The features are cracked for licensed users.
(some are partially working)

I'll work it all out once we got the license crack done :)

**Comment by WubTheGame** [comment]
But what I'm trying to ask is what's the point of "cracked for licensed users"? What's the difference between cracked and not cracked for a licensed user then?

**Comment by RedDot-3ND7355** [comment]
> But what I'm trying to ask is what's the point of "cracked for licensed users"? What's the difference between cracked and not cracked for a licensed user then?

Re-read what I said above. 
The current "crack" is for the features FOR licensed users.
the actual license "crack" is being worked on...

**Comment by RebornZA** [comment]
> But what I'm trying to ask is what's the point of "cracked for licensed users"? What's the difference between cracked and not cracked for a licensed user then?

Because you could buy $7 base license and then crack the rest of the features instead of paying $29 or more if you get it feature by feature. Thats the point.

**Comment by WubTheGame** [comment]
> > But what I'm trying to ask is what's the point of "cracked for licensed users"? What's the difference between cracked and not cracked for a licensed user then?
> 
> Because you could buy $7 base license and then crack the rest of the features instead of paying $29 or more if you get it feature by feature. Thats the point.

Thank you. That makes it perfectly clear.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
