### ISSUE TITLE
Features unlocked, but still tells me my trial is over.

### ISSUE THREAD

**Issue by Ilya1933** [RedDot-3ND7355/reWASD#2]
The crack in general seems to work, but whenever I hope the software, I get a message saying that my trial has expired. I think that this is because I went through the 7 days trial last year, and even after uninstalling and reinstalling reWASD, it remembers. This means that none of the features of reWASD work, not even the basic ones.

**Comment by RedDot-3ND7355** [comment]
Scrapped the entire crack and started from scratch. Will have it ready soon! :)

**Comment by RedDot-3ND7355** [comment]
Found a method for the crack to work with fake license and also unlocked all features.
Will update the git soon-ish today or tmr max. 💯

**Comment by AerYareli** [comment]
Any updates on this? I so badly want to try the Radial Menu! <3 Thank you!

**Comment by RedDot-3ND7355** [comment]
> Any updates on this? I so badly want to try the Radial Menu! <3 Thank you!

That method couldn't work because there was a signature check of some sort. So I had to resort to live memory editing.
Will let everyone know of any progress made
