### ISSUE TITLE
it's working in warzone 3 now?

### ISSUE THREAD

**Issue by bbb8993** [RedDot-3ND7355/reWASD#20]
it's working in warzone 3 now?

**Comment by RedDot-3ND7355** [comment]
You can "bypass" by using this.
[rewasd  hider.zip](https://github.com/RedDot-3ND7355/reWASD/files/14424083/rewasd.hider.zip)

How to use below.

How to run COD without uninstalling reWASD:
After running the Disable reWASD.bat (as admin) -> reboot pc and voila!

How to re-enable reWASD for other stuff other than COD (obviously):
Run the Enable reWASD.bat (as admin) -> reboot pc and voila!

**Comment by shardyy** [comment]
its gonna work in cod after hiding it?

**Comment by RedDot-3ND7355** [comment]
> its gonna work in cod after hiding it?

No. AS I stated. It only hides reWASD. So you don't have to uninstall it for cod to work.
The only way we could make it work with cod is by renaming the driver for it and reWASD would have to make a few changes for that to happen.

**Comment by shardyy** [comment]
so its hard to do probably? because there is no good bypass except vm

**Comment by RedDot-3ND7355** [comment]
> so its hard to do probably? because there is no good bypass except vm

It's not bad, but extra hassle. All goe s down to how you want it :)
VM and external PC is the way to go for reWASD to work with cod ATM.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
