### ISSUE TITLE
Unsure if I'm doing it correctly

### ISSUE THREAD

**Issue by SlimeyDimey23** [RedDot-3ND7355/reWASD#23]
I've downloaded the installer and placed the DLL's into the installation folder (unblocked) but I might've fucked it up somehow cause I keep getting this: 
![image](https://github.com/RedDot-3ND7355/reWASD/assets/161499860/857ea79f-222f-4011-b2b8-e3d522ec5152)

Am I doing something wrong that causes me to keep needing to update? I have a license and everything not that I can even input it it in without updating.

**Comment by SlimeyDimey23** [comment]
Nevermind, I realize even more that I mustve done it incorrectly since I clicked the buy now button that allowed me to post in my license key however none of the features work outside of the one I bought. 

![image](https://github.com/RedDot-3ND7355/reWASD/assets/161499860/4f08718a-2095-4d45-aef1-8efdf0282e89)

**Comment by RedDot-3ND7355** [comment]
reapply the cracked dll's.

**Comment by SlimeyDimey23** [comment]
Thx, it seemed like the dll's weren't properly unblocked.
