### ISSUE TITLE
Crack not working

### ISSUE THREAD

**Issue by chewio12** [RedDot-3ND7355/reWASD#24]
I have bought a license for ReWASD, and applied the crack but no features were unlocked. I double checked the dlls to make sure they were unblocked and did a fresh install of everything but still no dice.

**Comment by RedDot-3ND7355** [comment]
Did you install the proper version?

**Comment by sagaopc** [comment]
yes, the Rewasd is poping to update and saying without update, the program won't work. In the fact, rewasd open, but doesn't active the gamepad

**Comment by sagaopc** [comment]
![10-37-45](https://github.com/RedDot-3ND7355/reWASD/assets/1999256/811c8945-f046-4d44-902e-5f3ad1733a8b)
![reWASD 10-38 (2)](https://github.com/RedDot-3ND7355/reWASD/assets/1999256/9f510d83-b68d-4858-aa22-6a0c4ffad310)
![reWASD 10-38](https://github.com/RedDot-3ND7355/reWASD/assets/1999256/c978482e-a066-4c6d-acd5-30f64728d964)

**Comment by chewio12** [comment]
> Did you install the proper version?

Yes, I already had this version before but to be safe I did a full uninstall and reinstall using your provided links

**Comment by RedDot-3ND7355** [comment]
> > Did you install the proper version?
> 
> Yes, I already had this version before but to be safe I did a full uninstall and reinstall using your provided links

So you did the following:
1: Reinstalled
2: Activated License
3: Closed reWASD completely & From the tray
4: Applied the crack (the 2 dll's, in the folder of reWASD - where the executable is located at)
5: Unblocked both dll's in their properties
[6: Started reWASD, then check your license features at the top right. And everything should be unlocked.]

I assume you did all of these in the following order and step 6 did not work?

**Comment by sagaopc** [comment]
I'm sorry, I didn't notice the crack is a unlock to full version of the Rewasd, than I did not activate before use dlls... Now it's working flawless!

**Comment by chewio12** [comment]
> > > Did you install the proper version?
> > 
> > 
> > Yes, I already had this version before but to be safe I did a full uninstall and reinstall using your provided links
> 
> So you did the following: 1: Reinstalled 2: Activated License 3: Closed reWASD completely & From the tray 4: Applied the crack (the 2 dll's, in the folder of reWASD - where the executable is located at) 5: Unblocked both dll's in their properties [6: Started reWASD, then check your license features at the top right. And everything should be unlocked.]
> 
> I assume you did all of these in the following order and step 6 did not work?

Correct. I repeated the process to make sure I didn’t screw something up. The features will show they are unlocked until I actually try and use them and then it will grey out and and make me pay.

**Comment by RedDot-3ND7355** [comment]
> > > > Did you install the proper version?
> > > 
> > > 
> > > Yes, I already had this version before but to be safe I did a full uninstall and reinstall using your provided links
> > 
> > 
> > So you did the following: 1: Reinstalled 2: Activated License 3: Closed reWASD completely & From the tray 4: Applied the crack (the 2 dll's, in the folder of reWASD - where the executable is located at) 5: Unblocked both dll's in their properties [6: Started reWASD, then check your license features at the top right. And everything should be unlocked.]
> > I assume you did all of these in the following order and step 6 did not work?
> 
> Correct. I repeated the process to make sure I didn’t screw something up. The features will show they are unlocked until I actually try and use them and then it will grey out and and make me pay.

It's alright, we finally managed to get a full crack working :)
