### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AmrKhan25** [RedDot-3ND7355/reWASD#26]
this is probably a rewasd specific issue but I'm asking here because I can't find a fix anywhere
after installing and restarting I try to open rewasd and I get this
![image](https://github.com/RedDot-3ND7355/reWASD/assets/108533898/71eb2bb8-3191-43c1-9f15-025dea3500aa)
I tried your provided exe, and EugeneSunrise's one but still the same
I tried the official forum suggestion​ and nothing happened
![image](https://github.com/RedDot-3ND7355/reWASD/assets/108533898/f0c743bf-a3d3-47ff-8182-3358efea91bf)
any help please ?

**Comment by RedDot-3ND7355** [comment]
> > Do you have an anti-virus or other firewall installed?
> 
> No, just windows defender and I even disabled it but no luck

![image](https://github.com/RedDot-3ND7355/reWASD/assets/6676924/f34ae54e-80f6-4b55-9e7e-c769b2897d21)

Something is blocking your installer.

**Comment by AmrKhan25** [comment]
I'm considering reinstalling windows but I was leaving it as a last solution

**Comment by RedDot-3ND7355** [comment]
> I'm considering reinstalling windows but I was leaving it as a last solution

Don't bother reinstalling windows if you don't even know what's blocking it in the first place.
Can't guarantee it'll work even after formatting.

**Comment by Animawesome** [comment]
Its like you just forgot the installer in the zip or something I havent had an anti virus on for years, even the version before latest didnt have the installer in it.

**Comment by AmrKhan25** [comment]
> Don't bother reinstalling windows if you don't even know what's blocking it in the first place. Can't guarantee it'll work even after formatting.

It did the trick. Though I would've preferred an easier solution. 
It was already a 2 years-ish old system so probably something I installed prevented rewasd from working
Thank you ✌🏻

**Comment by AmrKhan25** [comment]
I think I figured it out. I was using rectify11 in the old windows and after I installed it in the new one, rewasd gave me the same error. Uninstalled rectify and rewasd worked again
A bummer but I will take rewasd over rectify
