### ISSUE TITLE
ReWASD mobile companion app

### ISSUE THREAD

**Issue by Not-Storm** [RedDot-3ND7355/reWASD#27]
as the title says, the mobile app of ReWASD, which can be used with it to unlock even more possibilities, doesn't works at the moment, will it be possible to make it work? 

I did try to use it, it works on the laptop but any action on the phone results in a msg saying, this app's license must be bought, open ReWASD on your PC to know details. 

I was just wondering if it will be possible to make it work in future?

**Comment by RedDot-3ND7355** [comment]
Mobile Companion app works with the 7.0 Crack v2 ATM.
7.1 Crack is still in the making.

It works fine on Android, Haven't tried IOS.


Make sure you used the proper crack <3

**Comment by Not-Storm** [comment]
Oh yes, I am sorry for the error on my part. I never realised I have been using 7.1

I am really sorry, thank you for the help

btw, amazing work, thanks a lot, my gratitude <3 really appreciate it
