### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Jadonas** [RedDot-3ND7355/reWASD#29]
Do you think its possible to edit driver name and change driver name in executable to bypass cod ricochet's controls?

**Comment by RedDot-3ND7355** [comment]
Sorry, I won't be partaking in this activity. It will attract too much attention toward me as an individual.

Here's a simple steps to proceed (although far from simple):
1: Rename driver & reinstall
2: Use DnSpy to change driver name in executable
3: Re-run reWASDService, Engine, UI under different names to avoid detection as well.

I will not say anything more, and wish you good luck!
