### ISSUE TITLE
still cant apply slots

### ISSUE THREAD

**Issue by goofyguy72** [RedDot-3ND7355/reWASD#30]
i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens

**Comment by RedDot-3ND7355** [comment]
> i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens

Beta crack doesn't work. Use the latest 7.0 Crack.

**Comment by goofyguy72** [comment]
> > i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens
> 
> Beta crack doesn't work. Use the latest 7.0 Crack.

I have and the same issue occurred

**Comment by RedDot-3ND7355** [comment]
> > > i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens
> > 
> > 
> > Beta crack doesn't work. Use the latest 7.0 Crack.
> 
> I have and the same issue occurred

Did you follow the steps in the readme, if you skipped one, it will not work.

**Comment by goofyguy72** [comment]
> > > > i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens
> > > 
> > > 
> > > Beta crack doesn't work. Use the latest 7.0 Crack.
> > 
> > 
> > I have and the same issue occurred
> 
> Did you follow the steps in the readme, if you skipped one, it will not work.

ill go through the steps again to make sure

**Comment by goofyguy72** [comment]
> > > > i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens
> > > 
> > > 
> > > Beta crack doesn't work. Use the latest 7.0 Crack.
> > 
> > 
> > I have and the same issue occurred
> 
> Did you follow the steps in the readme, if you skipped one, it will not work.

I uninstalled, reinstalled everything, went through all the steps and I still have this problem

**Comment by RedDot-3ND7355** [comment]
> > > > > i've tried the beta and most recent release and neither work, hitting apply just makes the button gray for like 2 seconds and then nothing happens
> > > > 
> > > > 
> > > > Beta crack doesn't work. Use the latest 7.0 Crack.
> > > 
> > > 
> > > I have and the same issue occurred
> > 
> > 
> > Did you follow the steps in the readme, if you skipped one, it will not work.
> 
> I uninstalled, reinstalled everything, went through all the steps and I still have this problem

Ain't got a clue why it wouldn't work other than anti-virus i guess(if you have one other than windows defender)

I tested it last night and was working fine and same for the other users.

There's something preventing the crack from working.
