### ISSUE TITLE
Cracked successfully, with a few days to appear problems

### ISSUE THREAD

**Issue by Dididididii** [RedDot-3ND7355/reWASD#31]
Why crack successfully used a few days will show this, click on the same setting will not take effect
![图片](https://github.com/RedDot-3ND7355/reWASD/assets/96111443/acbbad8d-3071-496d-9212-32baae95fff5)

**Comment by RedDot-3ND7355** [comment]
Re-add the cracked DLL's and unblock them. Should work again afterwards.
It reset's every 1st of the month

**Comment by Dididididii** [comment]
What if the DLL property does not unlock the selection box?
![q](https://github.com/RedDot-3ND7355/reWASD/assets/96111443/17b88415-9d06-4204-965f-4cddb99d8e93)

**Comment by RedDot-3ND7355** [comment]
> What if the DLL property does not unlock the selection box? ![q](https://private-user-images.githubusercontent.com/96111443/318802357-17b88415-9d06-4204-965f-4cddb99d8e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzUzNTcsIm5iZiI6MTcxMjA3NTA1NywicGF0aCI6Ii85NjExMTQ0My8zMTg4MDIzNTctMTdiODg0MTUtOWQwNi00MjA0LTk2NWYtNGNkZGI5OWQ4ZTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODliZDU2YmRiZjZmM2M5MDE0OGI5OGM2ZDYzNTQ1ZjlkMDRjZDg4ZTgzODQ4ZGY5Y2EzMDRjNGE0ZTViYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vMlp0CvymkVBmSAsOs6tOnR-ghzn4ywtjC9DvS0GvJs)

That means it's not blocked by Defender

**Comment by RedDot-3ND7355** [comment]
Also, don't use the 7.1 Crack. If you want a full crack use the 7.0 crack v2...
