### ISSUE TITLE
Popups appearing on start on latest reWASD-7108668

### ISSUE THREAD

**Issue by Mahasvan** [RedDot-3ND7355/reWASD#32]
Several popups such as these appear when starting the app, and I cannot find a way to disable them

![image](https://github.com/RedDot-3ND7355/reWASD/assets/82939599/ab6a766f-4265-49aa-b5a8-8f73ceb302e5)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/82939599/be43fa7a-f3d5-4ad5-93d2-7695a5d6e524)

**Comment by RedDot-3ND7355** [comment]
You can't disable them and they're part if the beta for 7.1.

If you don't want the popups, use the previous crack relewsed 7.0 v2

**Comment by Mahasvan** [comment]
My bad, thanks for your amazing work!
