### ISSUE TITLE
it never turns on??

### ISSUE THREAD

**Issue by SaCcRiFiCeR** [RedDot-3ND7355/reWASD#33]
![Screenshot_2](https://github.com/RedDot-3ND7355/reWASD/assets/166155399/73144301-2822-499b-9625-83633188888a)
![Screenshot_3](https://github.com/RedDot-3ND7355/reWASD/assets/166155399/c2bde8d2-6c89-4ee5-8d10-bd7ab1226330)

**Comment by RedDot-3ND7355** [comment]
Which version?

**Comment by TurneX** [comment]
me to

**Comment by RedDot-3ND7355** [comment]
> me to

which version...

**Comment by TurneX** [comment]
> > me to
> 
> which version...

the last version : reWASD-7108668

**Comment by EbiDesa** [comment]
also for me, the last version : reWASD-7108668 not turn on

**Comment by RedDot-3ND7355** [comment]
IF you all have a valid license, USE the 7.1 Beta Crack v2 to unlock all features.
Here: https://github.com/RedDot-3ND7355/reWASD/releases/tag/7.1.0.8668v2

IF you don't have a valid license and no feature either, USE the 7.0 Crack to bypass license check and unlock all features.
Here: https://github.com/RedDot-3ND7355/reWASD/releases/tag/7.0.0.8447v2
