### ISSUE TITLE
EDIT #3 :  4-20-24    lesser freedom then yesterday - with picture of ToS

### ISSUE THREAD

**Issue by psoizzac** [RedDot-3ND7355/reWASD#35]
**A NOTED THANK YOU Red dot - for doing such a nice service for us in the git, this business doesn't respect freedom of use to purchase, and you tried to give us that freedom to use what we bought. I appreciate you.**

----------------------

IMPORTANT 1: update: April 18th - seems it has been patched, (it must have a silence patcher in the app trying to call home and replace files on detection.) I can no longer use the apply button, does nothing.  

IMPORTANT 2 : Update number 2: REWASD-Daemon tools is removing all versions of REWASD that are 7.0 and 7.1 from their archive downloads, i can't even download it as a license user  anymore. and even if attempting to reinstall a older version, they have locked the user from activating the software on that system that is "Old Versions" .  They are now strengthening security and removing compromising vulnerabilities.         

NOTE SUGGESTION: Open a hidden discord for future projects based on this topic development. , can leave bread crumbs vague with just a pastebin link to live development activities using your profiles reputation ,to a disc DM server. - can keep code hidden in development chats moderation and make public when perfected development release. 

FINAL REPORT: UPDATE 3: (uploaded REWASD discord message about the patch and tightened security.)

![image](https://github.com/RedDot-3ND7355/reWASD/assets/138096153/8669535f-4bdc-4138-9697-0ab9bf71480f)

![324148738-33aa83d2-94f5-4dd4-a996-cc81815bb8d5](https://github.com/RedDot-3ND7355/reWASD/assets/138096153/8dc6f68b-51ea-4610-85aa-5614217d19b8)

UPDATED ToS Today 4/20/24 -  

![image](https://github.com/RedDot-3ND7355/reWASD/assets/138096153/b65cb61f-f72c-4601-a4e5-d18579205ab3)

**Comment by phanomgames** [comment]
Yeah apply button no longer works, they somehow patched it.

**Comment by Trex386** [comment]
It looks like REWASD wants to battle back again this

**Comment by psoizzac** [comment]
to confirm the rest of the report. UPDATE 3: 
![image](https://github.com/RedDot-3ND7355/reWASD/assets/138096153/33aa83d2-94f5-4dd4-a996-cc81815bb8d5)

**Comment by psoizzac** [comment]
They updated their Terms of service and made it worse today.
Now they can delete your account if you revoke your license to much. Lesser freedom then yesterday. 

![image](https://github.com/RedDot-3ND7355/reWASD/assets/138096153/44e120a3-eb04-4da8-bffb-c76bf89adbf1)

**Comment by RedDot-3ND7355** [comment]
Wow, they really did step up their game to a crisp. Software is more robust and secured against cracking.

I like to see that, but I quite don't agree with a few decisions they did and they properly shot themselves on their foot.
Hence all the drama lately.
