### ISSUE TITLE
Can 7.1 version run on apex?

### ISSUE THREAD

**Issue by SmallSideOUO** [RedDot-3ND7355/reWASD#36]
apex has an issue is that when you were using rewasd during the game
it will kick you out like this
![image](https://github.com/RedDot-3ND7355/reWASD/assets/33563641/afab5bbd-928d-4d1f-a095-bcbb94660776)

![image](https://github.com/RedDot-3ND7355/reWASD/assets/33563641/f38cf2fd-dc6d-4e27-85d2-8d5ae59a535e)

**Comment by SmallSideOUO** [comment]
https://www.youtube.com/watch?v=k__rrbh5un4
the more detail about my question

**Comment by SmallSideOUO** [comment]
https://github.com/RedDot-3ND7355/reWASD/assets/33563641/e5007b48-f8ad-45d1-a660-9ab34a740cfe

**Comment by SmallSideOUO** [comment]
https://github.com/RedDot-3ND7355/reWASD/assets/33563641/55a336b6-65b8-4344-af8b-555548b13723

**Comment by RedDot-3ND7355** [comment]
> 2024-04-21.00-35-45.mp4

rewasd is banned from apex.

**Comment by SmallSideOUO** [comment]
> > 2024-04-21.00-35-45.mp4
> 
> rewasd is banned from apex.

https://www.youtube.com/watch?v=He8FvuK5UPA&t=37s
how is it work?
is this real?

**Comment by psoizzac** [comment]
Small some of the REWASD discord has whispered about this source that it must be bought, i don't know if its r"Trusted" nor would i tend to it. risk is advised especially if keyloggers or AI adaptable malware is present.

**Comment by RedDot-3ND7355** [comment]
> Small some of the REWASD discord has whispered about this source that it must be bought, i don't know if its "Trusted" nor would i tend to it. caution is advised especially if keyloggers or AI adaptable malware is present in such trails of tools. I'd wait for multiple testimonies and testing on a VM if your suspicious about it. But do not get money stolen from you. you have been warned.

tool named re hid and does work. Tried it myself.

**Comment by psoizzac** [comment]
> tool named re hid and does work. Tried it myself.

That's great to hear Red. Man they updated their ToS today. I went ahead and updated my thread about it. It's more restrictive then it was yesterday. Man I'm starting to despise their method for something we bought.
