### ISSUE TITLE
Can't connect to switch by blue teeth,Repeatedly looping between steps

### ISSUE THREAD

**Issue by 1249747637** [RedDot-3ND7355/reWASD#37]
Uploading QQ录屏20240422222736.mp4…
![image](https://github.com/RedDot-3ND7355/reWASD/assets/119853922/921d76ea-6017-4dfb-8f82-9326edf7802c)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/119853922/9f1eaf24-1a9a-457c-afbe-603a6334bfc6)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/119853922/9f63a6e0-5f76-4b63-b5a7-19bffb8b2d92)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/119853922/b6f354f9-9e7c-47be-8805-033ae1a972ee)

**Comment by 1249747637** [comment]
QAQ
All the USB ports on my computer do not have wireless devices. My rewasd was first installed with version 8447, and then overwritten with the installation of 8668 (because I couldn't open the software when I first installed 8668)

**Comment by RedDot-3ND7355** [comment]
I don't know why this occurs.
I know it's been a while, but feel free to reopen this issue if it still persists. 
Perhaps the crack breaks this feature (but it shouldn't)
