### ISSUE TITLE
7.2 support? 

### ISSUE THREAD

**Issue by CjPhoenix** [RedDot-3ND7355/reWASD#38]
Wondering if 7.2 support is showing up any time soon? The live vibration testing and gyro support are both something I've been looking around for.

**Comment by RedDot-3ND7355** [comment]
> Wondering if 7.2 support is showing up any time soon? The live vibration testing and gyro support are both something I've been looking around for.

None sadly, 7.2 and above has security fixes preventing us from cracking it. Just like they stated it was made against us. Which is not a bad thing. They've made their app for robust and secured.

**Comment by kashifkhan0336** [comment]
What kinds of security fixes?

**Comment by RedDot-3ND7355** [comment]
> What kinds of security fixes?

as i mentioned above.
to prevent our methods to crack it

**Comment by Genobee99** [comment]
At least you gave us a version that in case the group disappears or dissolves, I can continue using it offline without a weekly online activator.
