### ISSUE TITLE
Remap No Turn on

### ISSUE THREAD

**Issue by EbiDesa** [RedDot-3ND7355/reWASD#39]
Hello. I am using Beta Crack v2, but when I click on Apply to Slot, nothing happens. 🤔 (Watch the video)

https://github.com/RedDot-3ND7355/reWASD/assets/112101494/e8a90961-f4f3-4e0c-a1af-7d9064e5a392

**Comment by RedDot-3ND7355** [comment]
it requires a valid license to use beta crack v2...
please read the readme entirely :)
