### ISSUE TITLE
Can't turn on remapping

### ISSUE THREAD

**Issue by SkyCaspian** [RedDot-3ND7355/reWASD#41]
![Desktop Screenshot 2024 05 11 - 16 21 27 47](https://github.com/RedDot-3ND7355/reWASD/assets/112041415/19471eba-771f-436a-89e6-8d2520bed788)

Left to the Apply Slot 1, the Power button is grayed out, and I'm unable to turn it on. I didn't use the beta files. These are from Version 700-8447. And I also did replace the dll files that were included in the .zip. 
When I go to the properties, I do not get the option to unblock the files

**Comment by RedDot-3ND7355** [comment]
if the dlls are placed in good folder and unblocked as mentioned for 700 it should works just fine :)

if issue still persists, feel free to reopen :)
