### ISSUE TITLE
Cannot activate remapping 

### ISSUE THREAD

**Issue by CodeSaturn-S** [RedDot-3ND7355/reWASD#42]
I am not able to activate the remapping, The Magic power button is grayed out and even after i set the mapping to slot 1 or any other slots it still doesnt work. i have tried restarting my pc and closing and reopening the app with task manager. I already have a valid License.

I downloaded the reWASD-7108668 from April 10, 2024

Thank you

**Comment by RedDot-3ND7355** [comment]
> I am not able to activate the remapping, The Magic power button is grayed out and even after i set the mapping to slot 1 or any other slots it still doesnt work. i have tried restarting my pc and closing and reopening the app with task manager. I already have a valid License.
> 
> I downloaded the reWASD-7108668 from April 10, 2024
> 
> Thank you

Did you follow the steps?

**Comment by CodeSaturn-S** [comment]
yea i put the dll files in the right place

**Comment by RedDot-3ND7355** [comment]
> yea i put the dll files in the right place and when i go into properties i dont see unblock

Did you try the 7.0 crack instead? I hear 7.1 have lots of issues with the crack as of lately with rewasd's desperate attempt to get rid of these cracks

**Comment by CodeSaturn-S** [comment]
tried downloading the zip for rewasd 7.0 but just says there a virus idk if i should be concerned

**Comment by RedDot-3ND7355** [comment]
> tried downloading the zip for rewasd 7.0 but just says there a virus idk if i should be concerned

false positive. They probably black listed 7.0 and 7.1 and removed support for these versions

**Comment by RedDot-3ND7355** [comment]
> 7.0 worked but now its saying that all of my devices arent connected

As weird as it can get.. Whelp. Sadly can't make magic happen if it doesn't work no more and steps have been followed.

Try to start via the engine first then gui and hit me back see if that works

**Comment by CodeSaturn-S** [comment]
wdym engine then gui

**Comment by RedDot-3ND7355** [comment]
> wdym engine then gui

where rewasd is installed at. There's an engine. make sure to close the engine(from the tray), apply crack then open the rewasdengine.exe. 
Then open the gui from the engine in the tray.

Let me know if that does anything 👌

**Comment by RedDot-3ND7355** [comment]
> it didnt help, it still shows all my devices grayed out

dunno how or why its not working.
I'll try it after work today and see if it still works

**Comment by CodeSaturn-S** [comment]
id appreciate it thank you.

**Comment by Scorpion1117** [comment]
Hey, a new version of Rewasd, 7.3, was released today that allows us to play Apex and Cod without having to uninstall the software. Can we get the crack of this

**Comment by RedDot-3ND7355** [comment]
> id appreciate it thank you

7.0 is the only working crack, if it doesn't completely work, then there's nothing I can do to help :C
