### ISSUE TITLE
Rewasd

### ISSUE THREAD

**Issue by Scorpion1117** [RedDot-3ND7355/reWASD#43]
Hey, a new version of Rewasd, 7.3, was released today that allows us to play Apex and Cod without having to uninstall the software. Can we get the crack of this

**Comment by RedDot-3ND7355** [comment]
> Hey, a new version of Rewasd, 7.3, was released today that allows us to play Apex and Cod without having to uninstall the software. Can we get the crack of this

as of rewasd 7.2, they patched our methods to apply the crack we used. so no, we won't be able to crack it.
