### ISSUE TITLE
Can't activate license in 7.1.0.8668

### ISSUE THREAD

**Issue by r5vx** [RedDot-3ND7355/reWASD#44]
I bought a key to activate reWASD, but it says that it has already been activated with the 0000000000000000 key. When I try to replace it with the correct key and click submit, it doesn't change. I am assuming this is the reason why the macro won't work in game when the free trial version did. 

My discord is r5vx, any help would be appreciated.
![image](https://github.com/RedDot-3ND7355/reWASD/assets/170718654/fb6bf5c2-9e68-4f02-a252-4e4ef65629e6)

**Comment by RedDot-3ND7355** [comment]
Hello! To apply your license, please delete the rewasd.dll. Apply it, then close rewasd completely again and re-apply the dll if you want. You don't need it, but using it will mark the gui as if u have all features  :)

**Comment by r5vx** [comment]
I deleted the reWASD.dll file and then tried opening reWASD but now it won't open. I tried restarting and fully closing it in task manager.

**Comment by RedDot-3ND7355** [comment]
> I deleted the reWASD.dll file and then tried opening reWASD but now it won't open. I tried restarting and fully closing it in task manager.

You have to fully close it then remove the dll. 
If that still won't work, remove the other dll as well.

**Comment by r5vx** [comment]
Its fully closed and both files are deleted. But it still won't open.

**Comment by RedDot-3ND7355** [comment]
> Its fully closed and both files are deleted. But it still won't open.

reinstall rewasd, apply license then fully close, apply rewasdcommon.dll in rewasd folder without the s

**Comment by r5vx** [comment]
now its given me this ;-; 
![image](https://github.com/RedDot-3ND7355/reWASD/assets/170718654/29b733bb-cd2d-4fe8-9718-eeca42a1284f)

**Comment by RedDot-3ND7355** [comment]
> now its given me this ;-; ![image](https://private-user-images.githubusercontent.com/170718654/333573809-29b733bb-cd2d-4fe8-9718-eeca42a1284f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTExOTMsIm5iZiI6MTcxNjU1MDg5MywicGF0aCI6Ii8xNzA3MTg2NTQvMzMzNTczODA5LTI5YjczM2JiLWNkMmQtNGZlOC05NzE4LWVlY2E0MmExMjg0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMTQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmNiYTU0ZGRkMzEyM2ZhN2Y3ZDQ5NWE4MjE3NzhlNWI4NzYxMDAzMWExZmEyNDdmNTVlZmJkZjFlZTk1OGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dFkJpAxloMKsICXkdeJR-c38L01PdBaED8-y2qXkRLg)

they removed support for the versions we cracked. FOR thar reason in itself.

I would require making a patch to always return a good status when processing network activity.

**Comment by r5vx** [comment]
What should I do? When I tried the older version it didn't detect my controller. Should I just spend $14 more dollars on the new version?

**Comment by RedDot-3ND7355** [comment]
You can use the 7.0 crack instead as it's the only crack working. 
Sadly can't make new crack as they patched our methods. 

Feel free to reopen this issues arise :)
