### ISSUE TITLE
can you crack the keyflexor program?

### ISSUE THREAD

**Issue by S1R1ME** [RedDot-3ND7355/reWASD#45]

**Comment by RedDot-3ND7355** [comment]
I need a valid subscription to try it out and see how it works.
should be able to judge from that if I can crack it or not :)

**Comment by S1R1ME** [comment]
I thought so, thanks for the reply)

**Comment by trevmont65** [comment]
this would be dope!

**Comment by luisfergz** [comment]
still in mind?

**Comment by Arish12233** [comment]
any update??

**Comment by RedDot-3ND7355** [comment]
I have not been provided and nor will I afford Keyflexor.
I don't plan on buying it either.

**Comment by RedDot-3ND7355** [comment]
Closing this issue

**Comment by VRAY-VRAY** [comment]
Hola saludos punto rojo-3nd7355, si me puedes mandar un mensaje yo no puedo mandarte un correo o algún mensaje al interno yo te voy a pasar en este momento el launcher y también la licencia que tengo para que lo puedas descomplar y lo puedes hacer gratuito háblame o escríbeme.

**Comment by Ma2929** [comment]
any updates vray-vray
