### ISSUE TITLE
Completely unable to launch the app. "Something prevents reWASD from normal functioning."

### ISSUE THREAD

**Issue by pellapellasekai** [RedDot-3ND7355/reWASD#47]
![image](https://github.com/RedDot-3ND7355/reWASD/assets/172324107/3c81f390-3fd2-454b-b0e3-5161e03dcc9b)

I am completely unable to open reWASD because I keep getting this message.
I have tried everything listed in the image to let reWASD through to no avail , alongside adding reWASD as an exception to the firewall manually.

**Comment by RedDot-3ND7355** [comment]
> ![image](https://private-user-images.githubusercontent.com/172324107/338345173-3c81f390-3fd2-454b-b0e3-5161e03dcc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTU3ODUsIm5iZiI6MTcxODA1NTQ4NSwicGF0aCI6Ii8xNzIzMjQxMDcvMzM4MzQ1MTczLTNjODFmMzkwLTNmZDItNDU0Yi1iMGUzLTUxNjFlMDNkY2M5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMTM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWYxNGIyMGYxYzhlNmJkYTFmZDE1MTU0NzEwZmQyYjlmNjUwZGE3OTNjZmNlMDU3NjM3YmUzYTA1ZGI0ZjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xaz7V2vxSJDJ19B3xYYaHzWOq0geEbiWbSRsXJdymzA)
> 
> I am completely unable to open reWASD because I keep getting this message. I have tried everything listed in the image to let reWASD through to no avail , alongside adding reWASD as an exception to the firewall manually.

that happens if the dll's are blocked. Have you tried following the steps in the readme?

**Comment by pellapellasekai** [comment]
I've unblocked the dll's in a previous version to no avail, and whilst I've tried to do the same in the one I'm using the option doesn't appear in properties.
![image](https://github.com/RedDot-3ND7355/reWASD/assets/172324107/fb3124da-2f22-47ac-b3f1-160395fb2800)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/172324107/98e73361-1cfe-452e-994f-90485a683f40)

Is there something I'm missing?

**Comment by RedDot-3ND7355** [comment]
> I've unblocked the dll's in a previous version to no avail, and whilst I've tried to do the same in the one I'm using the option doesn't appear in properties. ![image](https://private-user-images.githubusercontent.com/172324107/338361056-fb3124da-2f22-47ac-b3f1-160395fb2800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTY4NzUsIm5iZiI6MTcxODA1NjU3NSwicGF0aCI6Ii8xNzIzMjQxMDcvMzM4MzYxMDU2LWZiMzEyNGRhLTJmMjItNDdhYy1iM2YxLTE2MDM5NWZiMjgwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMTU2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDViYjk4NjQxYjM4NTBlM2I1ZTQ2NDI1ZmY0OTZhMmRmYmI3ZjI3NzA1MmM2ODBjNGQ1MDg1NmVlZjAxMmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SOZrrgCU2PqsNz4gnkVQhELsAOA_kz4jhnLoQWV252o) ![image](https://private-user-images.githubusercontent.com/172324107/338361156-98e73361-1cfe-452e-994f-90485a683f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTY4NzUsIm5iZiI6MTcxODA1NjU3NSwicGF0aCI6Ii8xNzIzMjQxMDcvMzM4MzYxMTU2LTk4ZTczMzYxLTFjZmUtNDUyZS05OTRmLTkwNDg1YTY4M2Y0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMTU2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmEyYjhkZDE2MTk4NjMyZGFjNTkwNzBlNzRmYmNlNWNmNTdhN2IxMzI5ZTYxODQ5MGU5N2ZkNzRiYTZhZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PQL6DMoEa9GHExkZjqaph6EzXgbA1-IzLNy6a-LtTIw)
> 
> Is there something I'm missing?

Have you completely closed rewasd/rewasdengine/rewasdservice before applying the crack?

**Comment by pellapellasekai** [comment]
I just uninstalled and reinstalled making sure to do that this time around. Still nothing :/

**Comment by RedDot-3ND7355** [comment]
> I just uninstalled and reinstalled making sure to do that this time around. Still nothing :/

I got no idea why then. Which version did you install?

**Comment by Areaxis** [comment]
Hi, I have the same problem and I did everything the readme said. The version I use in my case is 8447. There is no unblock option in my dlls. Please give me insight over this issue.

**Comment by EugeneSunrise** [comment]
[Solution](https://github.com/EugeneSunrise/reWASD/discussions/147)

**Comment by caoHenriques** [comment]
I had the same problem
this is what worked for me, I hope it helps anyone with the same issue

unistall reWASD, IMPORTANT -> check the two options to remove also previous settings and profiles
restart PC
Install the reWASD provided here in github, maybe IMPORTANT -> uncheck the option to send diagnostic data 
restart PC
unblock the two dll files, and copy past to the reWASD directory

good luck
