### ISSUE TITLE
Quick question and thank for the crack

### ISSUE THREAD

**Issue by phenix60** [RedDot-3ND7355/reWASD#48]
So after trying a bit i finally managed to install the cracked version thx and was wondering if you would maybe plan to update the crack to the current latest version 7.3.0.9159 ?

**Comment by RedDot-3ND7355** [comment]
> So after trying a bit i finally managed to install the cracked version thx and was wondering if you would maybe plan to update the crack to the current latest version 7.3.0.9159 ?

They sadly patched our cracking method.
So I won't be updating or making any new cracks for rewasd.

**Comment by Yoyojojo12** [comment]
@RedDot-3ND7355 How can I get in contact with you? I need to ask you about something

**Comment by RedDot-3ND7355** [comment]
> @RedDot-3ND7355 How can I get in contact with you? I need to ask you about something

Discord would be the best way.

**Comment by Yoyojojo12** [comment]
> > > > @RedDot-3ND7355 How can I get in contact with you? I need to ask you about something
> > > 
> > > 
> > > Discord would be the best way.
> > 
> > 
> > Alright, what is it so I can add you?
> 
> endlesskogaruh
> 
> i'll remove the id once you added me

Alright, adding now.
