### ISSUE TITLE
Apply to slot 1 Not Working.

### ISSUE THREAD

**Issue by craqedfn** [RedDot-3ND7355/reWASD#5]
After using it for a couple days, it just stopped working (applying and popping up that  my trial is over) upon this morning.
Here's everything I've tried to fix it, (my discord is nathanffn if you'd like to contact me aswell):
Rebooting
Turning off VPNs on startup
Admin
Unblocking DLLs
Logging Registry (on/off)
reinstalling
doing the buy now, activate way to  active my "lisence"
Different configs

**Comment by MaximDrop** [comment]
> После использования в течение нескольких дней он просто перестал работать (применяя и выскакивая, что моя пробная версия закончилась) сегодня утром. Вот все, что я пытался исправить (мой дискорд nathanffn, если вы хотите связаться со мной): Перезагрузка Отключение VPN при запуске Администратор Разблокировка библиотек DLL Ведение журнала реестра (вкл./выкл.) Переустановка Выполнив кнопку «Купи сейчас, активируй способ активировать мою лицензию» Различные конфигурации

У Вас заработало после этих манипуляций?

**Comment by craqedfn** [comment]
What do you mean by this?

**Comment by RedDot-3ND7355** [comment]
Will be updating the crack tomorrow or later today. Made it work for invalid licenses :)

**Comment by RedDot-3ND7355** [comment]
Closing this issue, duplicate of #1
