### ISSUE TITLE
Latest Crack

### ISSUE THREAD

**Issue by Ghost-Recon** [RedDot-3ND7355/reWASD#52]
Can you crack the latest version of rewsad cause the update allows you to play call of duty without uninstalling @RedDot-3ND7355

**Comment by Arish12233** [comment]
> > Can you crack the latest version of rewsad cause the update allows you to play call of duty without uninstalling @RedDot-3ND7355
> 
> Same thing I told the other users. They patched our methods of cracking it. So no foreseeable updates. ⚰️

will you u guys try to make crack or give up at this point?

**Comment by RedDot-3ND7355** [comment]
> > > Can you crack the latest version of rewsad cause the update allows you to play call of duty without uninstalling @RedDot-3ND7355
> > 
> > 
> > Same thing I told the other users. They patched our methods of cracking it. So no foreseeable updates. ⚰️
> 
> will you u guys try to make crack or give up at this point?

there's no holes left that we found during reversing. So there's nothing to work on.
