### ISSUE TITLE
rewasd checking license

### ISSUE THREAD

**Issue by Arish12233** [RedDot-3ND7355/reWASD#54]
rewasd says check license and the popup dissapears
it happens every 1 minute and remapping doesnt work on it

**Comment by RedDot-3ND7355** [comment]
> rewasd says check license and the popup dissapears it happens every 1 minute and remapping doesnt work on it

You didn't add the dll's or they'er blocked. Please follow the instructions provided in the readme :)

**Comment by RedDot-3ND7355** [comment]
Assuming you got it working! Closing this issue :)
