### ISSUE TITLE
license bypass not working 

### ISSUE THREAD

**Issue by whitefang640** [RedDot-3ND7355/reWASD#57]

**Comment by RedDot-3ND7355** [comment]
Which version did you try? Did you unblock the dll's?

**Comment by whitefang640** [comment]
i used the non beta and yes i did unblock them

**Comment by RedDot-3ND7355** [comment]
> i used the non beta and yes i did unblock them

Did you close rewasd completely before putting in the dll's?

**Comment by whitefang640** [comment]
yes
