### ISSUE TITLE
Paid features like radial menu still locked? 

### ISSUE THREAD

**Issue by pyro-lc** [RedDot-3ND7355/reWASD#7]
It says to buy a license or try a trial when I try to use the radial menu,  using english version, unblocking dlls is not an option as i dont see it in the properties, probably already unblocked by default.
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/1b128053-f252-4ac0-aaed-64cec9d29e1f)

![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/c19d6a21-11f7-4b1b-bbca-6d7760ce0ee4)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/a3c18203-e296-476c-8ba4-24ad1503f7c6)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/5b8a22aa-d3d9-46d0-84d6-01a044a57b0d)

**Comment by RedDot-3ND7355** [comment]
You checked the properties OF the dll's and not the folder? You placed both files in the rewasd folder(replaced the rewasd.dll)?

Tried clicking on "Try" for the radial as well?

**Comment by pyro-lc** [comment]
> You checked the properties OF the dll's and not the folder? You placed both files in the rewasd folder(replaced the rewasd.dll)?
> 
> Tried clicking on "Try" for the radial as well?

yea i did check and are already placed in the right rewasd folder (replaced rewasd.dll too)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/57c009b7-7ff6-4d08-8d9f-d07e5006f3de)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/7c50489a-095a-4665-88c4-031fdf7507c6)
![image](https://github.com/RedDot-3ND7355/reWASD/assets/154731623/ce4bf412-2550-4464-99de-08cbf7877c4c)

tried the "try" button, "buy" button, "refresh activation status" button. nothing helped

**Comment by nitay100** [comment]
did you buy rewasd license?

**Comment by RedDot-3ND7355** [comment]
If you have read the README properly, you'd know that the license isn't fully cracked yet.
(still a work in progress, no ETA due to holidays)
You can still use this "crack" to unlock all the features except for license.
and you can't unlock all the features if you don't have a valid license.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
