### ISSUE TITLE
Apply Button - non functional  however works with license

### ISSUE THREAD

**Issue by psoizzac** [RedDot-3ND7355/reWASD#8]
For those who uninstalled and kept data configuration and license data while uninstalling. - this will work for you as a "Offline" version 
however if you noticed that you can't use other features "accept the ones you bought."  Well then!; TLDR - its a dummy icon, a fake, it isn't active as it only looks at your license "FEATURES" you bought.    Now If however you got motivated and tried to wipe completely your license and data and give a clean install AND then tried to run this then you will notice now "Nothing works" Not even the apply button to remap functions. All the app is used for now is vibration and lights. - i explain this synopsis as a way to clear the air for Red to give insight of symptoms that might help correlate a culprit to this issue. - I hope this information helps.  UPDATE:  Correction it works til the 30 day recheck fails to connect to the internet. you must turn off firewall once, click apply button then turn your firewall on. - it failed it's check today offline, so that is a requirement to keep it offline for awhile. - this happened today on 1/8/24

**Comment by Nabeeh-AlSawaf** [comment]
personally i really think 1 issue is enough, just to not bloat the repo with info, either way thanks for the extra explanation !!! may Red manage to get through stuff successfully

**Comment by psoizzac** [comment]
> personally i really think 1 issue is enough, just to not bloat the repo with info, either way thanks for the extra explanation !!! may Red manage to get through stuff successfully

Not much explanation has been given in the repo other then symptoms, so as a continuation of such i went ahead and explained the situations to the symptoms so people who read it won't continue to pester. Rather my entry to be a burden its more like a warning sign.

**Comment by RedDot-3ND7355** [comment]
I thought I could manage to finish it before holidays. Sadly can't due to module not being found in memory somehow but is present on file.

So can't find the pattern to modify for bypassing license check on apply (and other functions related to "Remap")

Injection of external module wont work either.
Probably an issue with MemorySharp.
I could try another lib for that.

Until I figure out why it won't show in external/internal memory, I can't progress.


I'll update the repo for the extra symptoms and the following crack only works with a valid license(atm) and features are unlocked.

**Comment by psoizzac** [comment]
> I thought I could manage to finish it before holidays. Sadly can't due to module not being found in memory somehow but is present on file.

> I'll update the repo for the extra symptoms and the following crack only works with a valid license(atm) and features are unlocked.

Awe thanks Red for trying your best to give a us a gift for the holidays We appreciate you.   I will update to clarify in the base post that only "Features bought" . Don't burn your self out though! Enjoy family time to!

**Comment by yurrii22** [comment]
oh hey i have problem everthing is good ig but i cant scan my game or select it its not avalibale to select a program so any help please

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
