### ISSUE TITLE
cant scan my game or select it please need help

### ISSUE THREAD

**Issue by yurrii22** [RedDot-3ND7355/reWASD#9]
hey there ive been trying to fix this issue but i failed anyways when i try to scan a game or select i mean prossece it it seems offline or idk like i cant even click on it its not available and im talking about the associated apps option  so please someone help me with that

**Comment by RedDot-3ND7355** [comment]
You need a valid license before using the crack.

**Comment by yurrii22** [comment]
how????

**Comment by yurrii22** [comment]
bro if i have one why the hell i need crack

**Comment by RedDot-3ND7355** [comment]
> bro if i have one why the hell i need crack

read the readme on my git.

**Comment by RedDot-3ND7355** [comment]
> how????

https://github.com/RedDot-3ND7355/reWASD

**Comment by yurrii22** [comment]
i did but bro i can not find a way to get a  license

**Comment by RedDot-3ND7355** [comment]
> i did but bro i can not find a way to get a license

you gotta buy it from them. Thats how you get a license.

**Comment by RedDot-3ND7355** [comment]
https://github.com/RedDot-3ND7355/reWASD/issues/24#issuecomment-1975395283
